apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: weather-nodejs-app-pipelinerun-weather-nodejs-app-bluegreen-
spec:
  params:
    - name: app-name
      value: weather-nodejs-app-bluegreen
    - name: source-repo
      value: 'https://github.com/cloud-native-garage-method-cohort/squad1-front' 
    - name: image-repo
      value: quay.io/rdemayo/weatherapp
    - name: revision
      value: feature-new-color
  pipelineRef:
    name: weather-nodejs-app-bluegreen
  serviceAccountName: build-bot
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: gitops-repository
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
